### ISSUE TITLE
Webhook design

### ISSUE THREAD

**Issue by janko** [samharnack/shrine-encoder#3]
Hi Sam,

I noticed your two recent Shrine-related projects, shrine-encoder and shrine-webhook. I'm reaching out because I recently finished an integration for [Transloadit](https://transloadit.com/), a service similar to Zencoder.

https://github.com/janko-m/shrine-transloadit

Since Transloadit also uses webhooks to notify you when processing is done, I was initially looking whether I could use shrine-webhook, or at least make some necessary PRs. However, at the end I went with my own approach which works really nicely, and just wanted to share it with you in case you want to do something like that in shrine-encoder.

So, in shrine-transloadit I relied on the ability to add some JSON payload when submitting my processing request, and that this same JSON will be returned to me in the webhook. This allowed me to achieve the same idea as with backgrounding jobs, that in the webhook I have all the information about which record and attachment it belongs to and instantiate all of these objects, and that I can just transform the result in Shrine's attachment format and save it to the database.

It was also really easy to allow putting that processing request in a background job, which is nice because this HTTP request doesn't actually need to be performed in the foreground.

Anyway, just wanted to let you know, so that maybe it gives you some ideas how to finish shrine-encoder.

Cheers,
Janko

**Comment by samharnack** [comment]
Hey Janko!

Thank you for your feedback, I'm just now seeing it :/ I will definitely look at your implementation. 

-Sam
